apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-ui
  labels:
    app: chat-app-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-ui
  template:
    metadata:
      labels:
        app: chat-app-ui
    spec:
      containers:
      - name: go-chat-app
        image: animus123/go-chat-app-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: GO_BACKEND
          value: http://go-chat-app:30029

---

apiVersion: v1
kind: Service
metadata:
  name: chat-app-ui-service
spec:
  type: NodePort
  selector:
    app : chat-app-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30022                                           